### ISSUE TITLE
Data format of the float32 input data file 

### ISSUE THREAD

**Issue by Datavizcowboy** [VulcanTechnologies/d3-grid-map#16]
I have tried to represent an oceanic variable (oxygen) sampling a NetCDF file to create a .txt file via Python with latitude, longitude and the variable. But despite playing with different combinations in the column order and the grid size (360 x 180) I couldn't make a correct projection (see .jpg). 

It is not clear to me what the structure of the float32 .dat file has to be in order to distribute the lat-lon datapoints properly. Is it derived from a GRIB or a NetCDF file? If so, how?

Thanks!

![example_latlonvar](https://cloud.githubusercontent.com/assets/26009155/26562372/12016f3e-44c6-11e7-98c9-45e552459623.jpg)

**Comment by jsheedy** [comment]
Thanks for writing in, we'll work on getting better (some!) documentation for the data format.

The test data gets loaded in index.html as a typed Javascript Float32Array:

          d3.xhr('data/float32.dat')
            .responseType('arraybuffer')
            .get(function(error, xhr) {
              var data = new Float32Array(xhr.response);

To add binary data to the map, just pass it to the addLayer method:

    map.addLayer(data, layerOptions);

addLayer will call the appropriate data transformation method, which in this case is 

    DataImport.arrayToGrid

arrayToGrid expects the passed array to be one dimensional in row-major order. So to get something like GRIB or NetCDF imported, you will have to convert it to this format. addLayer expects a Javascript typed array. It would make sense to make changes to accept a regular javascript array too, and of course a pull request for importing other data formats would be appreciated :)

The demo data in data/float32.dat has one float32 value per cell in row major order. It is sparse data so most of the values are NaN. These arrays compress well with gzip between the server and browser. This data was produced from a Python numpy array with something like this:
    numpy_array.astype(np.float32).tobytes()

Will this help you get things going? If it's not working and you can post some code or data I'd be happy to take a look.

**Comment by jsheedy** [comment]
I'll have to say though that your screenshot is beautiful as is. As a glitcher, a colleague pointed out that your problem is my art form :)

**Comment by Datavizcowboy** [comment]
Haha, indeed.  :D

Yes, very helpful hint on the data format conversion using: 
`numpy_array.astype(np.float32).tobytes()`

All in all, from a NetCDF:

`import netCDF4
import numpy as np

nc = netCDF4.Dataset('./World_Ocean_Atlas.nc')
oxygen = nc.variables['O2_LINEAR'][:,:,:,:]

oxy=[]

for j in range(len(oxygen[0][0])-1,0,-1):
    for i in range(0,len(oxygen[0][0][0]),1):
             oxy.append(np.mean(oxygen[1,10:15,j,i]))
             
foxy=np.array(oxy)
doxy=foxy.astype(np.float32).tobytes()
np.save('./Oxy_in_float32_binary.dat', doxy)`

I was missing that last bit. It looks much better now ! 

Thanks !

![projection](https://cloud.githubusercontent.com/assets/26009155/26724033/9b9f026e-4797-11e7-9fda-a1026db5d884.jpg)

**Comment by jsheedy** [comment]
I'm glad that helped, it's looking good! I've seen that background fill of purple problem before, and just created [Issue #17](https://github.com/VulcanTechnologies/d3-grid-map/issues/17) for it.
